version: "3"
services:
  frontend:
    build: ./frontend
    command: serve -s build -l 3000
    container_name: realworld-docker-frontend
    stdin_open: true
    tty: true
    restart: unless-stopped
  api:
    build: ./api
    command: npm run start
    container_name: realworld-docker-api
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    container_name: realworld-docker-api-db
    volumes:
      - mongodb_api:/data/db
  auth:
    build: ./auth
    command: npm run start
    container_name: realworld-docker-auth
    environment:
      - PORT=3001
      - HOST=http://realworld-docker.com/auth
      - MONGO_URL=mongodb://auth_db:27017/api
    depends_on:
      - auth_db
  auth_db:
    image: mongo:latest
    container_name: realworld-docker-auth-db
    volumes:
      - mongodb_auth:/data/db_auth
  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth_db
volumes:
  mongodb_api:
  mongodb_auth: