version: "3"
services:
  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
  frontend:
    command: npm run start
    volumes:
      - ./frontend/src:/usr/src/frontend/src
    stdin_open: true
    tty: true
    restart: unless-stopped